#!/bin/bash

SETUP_PATH="$HOME/setup"

if [ ! -e $SETUP_PATH/laptop/mac ]; then
  mkdir -p $SETUP_PATH && cd $SETUP_PATH && git clone git@github.com:machupicchubeta/laptop.git
fi

$("$SETUP_PATH/laptop/mac")
